### ISSUE TITLE
when i depoy the net the error occurs

### ISSUE THREAD

**Issue by Lvhhhh** [dwofk/fast-depth#1]
=> [TVM on TX2] using model files in ../tvm_compile/tx2_cpu_mobilenet_nnconv5dw_skipadd_pruned/
=> [TVM on TX2] loading model lib and ptx
Traceback (most recent call last):
  File "tx2_run_tvm.py", line 91, in <module>
    main()
  File "tx2_run_tvm.py", line 88, in main
    run_model(args.model_dir, args.input_fp, args.output_fp, args.warmup, args.run, args.cuda,  try_randin=args.randin)
  File "tx2_run_tvm.py", line 13, in run_model
    loaded_lib = tvm.module.load(os.path.join(model_dir, "deploy_lib.o"))
  File "/home/lvhao/tvm/python/tvm/module.py", line 216, in load
    _cc.create_shared(path + ".so", path)
  File "/home/lvhao/tvm/python/tvm/contrib/cc.py", line 33, in create_shared
    _linux_shared(output, objects, options, cc)
  File "/home/lvhao/tvm/python/tvm/contrib/cc.py", line 58, in _linux_shared
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/usr/bin/ld: ../tvm_compile/tx2_cpu_mobilenet_nnconv5dw_skipadd_pruned/deploy_lib.o：普通ELF重定位（M: 183）
/usr/bin/ld: ../tvm_compile/tx2_cpu_mobilenet_nnconv5dw_skipadd_pruned/deploy_lib.o：普通ELF重定位（M: 183）
../tvm_compile/tx2_cpu_mobilenet_nnconv5dw_skipadd_pruned/deploy_lib.o: 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status

**Comment by dwofk** [comment]
Hi,

Could you please provide more information about the system on which you are running? Are you getting this error on an NVIDIA Jetson TX2 platform?

The model that you are trying to load was compiled specifically to run with CUDA 8.0 on the TX2.

**Comment by Trinity-Actual** [comment]
Hi,

Was wondering if this error was resolved? I'm getting the same issue when i try to run the compiled model on my computer.
I'm on Cudatoolkit 10.2. is it only compatible with Cuda 8.0?


  File "/home/ubuntu/.conda/envs/Labyrinth/lib/python3.7/site-packages/tvm/contrib/cc.py", line 132, in _linux_compile
    raise RuntimeError(msg)

RuntimeError: Compilation error:
/usr/bin/ld: results/tvm_compiled/tx2_cpu_mobilenet_nnconv5dw_skipadd_pruned/deploy_lib.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: results/tvm_compiled/tx2_cpu_mobilenet_nnconv5dw_skipadd_pruned/deploy_lib.o: Relocations in generic ELF (EM: 183)
results/tvm_compiled/tx2_cpu_mobilenet_nnconv5dw_skipadd_pruned/deploy_lib.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status

Thanks!

**Comment by dwofk** [comment]
Hi @Trinity-Actual,

The compiled models in this repo were indeed compiled with the backend set as CUDA 8.0 and are likely not compatible with newer versions of CUDA. This is because the compilation process itself is CUDA version-specific. In this case, the original models would need to be re-compiled using TVM with the backend set as CUDA 10.2.

**Comment by Ruinmou** [comment]
Has this problem been solved? The same problem occurs when I run under Ubuntu 18 and CUDA 10.2. Without using the GPU as CPU model, this problem still exists. Is there any good solution?
TVM specifies CUDA 10.2
