### ISSUE TITLE
Problem running the evaluation code

### ISSUE THREAD

**Issue by GustavoCamargoRL** [dwofk/fast-depth#10]
Hi, 
I'm trying to run FastDepth, in a ubuntu 18, with CUDA 9.1, pytorch 1.2. But with no success when running "python3 main.py --evaluate [path_to_trained_model]". i'm getting the following error message "transforms.py", line 337, in __call__
    return misc.imresize(img, self.size, self.interpolation)
AttributeError: module 'scipy.misc' has no attribute 'imresize' "
So first, do you know which version of scipy do you use?
And, a tried all the pretrained models in "http://datasets.lids.mit.edu/fastdepth/results/" except for the tvm folder, but i don't know, which one can i use without an embedded system?

**Comment by dwofk** [comment]
Hi @GustavoCamargoRL,

We use scipy v1.0.0 and v1.1.0 on our systems.

All of the pretrained models outside of the tvm folder can be loaded in PyTorch and used on any system running PyTorch; they can be used without an embedded system. Only the compiled models inside the tvm folder are limited to usage on a TX2 CPU/GPU.

**Comment by soldierofhell** [comment]
Hi @dwofk, it would be good to add requirements.txt for exact version or in this particular case replace scipy with PIL/skimage/opencv, because imresize is depreciated in scipy.

Regards,
