### ISSUE TITLE
Problem when try running evaluation

### ISSUE THREAD

**Issue by AldrichCabrera** [dwofk/fast-depth#12]
Hi, nice work. 
I'm trying run Evaluation code with CUDA 9.1, pytorch 1.2, but I'm getting the following error:

FileNotFoundError: [Errno 2] No such file or directory: '../data/nyudepthv2/val'

**Comment by MRinel** [comment]
Mybe you should use absolute path?

**Comment by liuxinshi** [comment]
> Hi, nice work.
> I'm trying run Evaluation code with CUDA 9.1, pytorch 1.2, but I'm getting the following error:
> 
> FileNotFoundError: [Errno 2] No such file or directory: '../data/nyudepthv2/val'

hi,please note that ‘./data ’和 ‘../data’ are different.
