### ISSUE TITLE
How to get the absolute distance from the camera to the object based on depth map?

### ISSUE THREAD

**Issue by MRinel** [dwofk/fast-depth#13]
Hi,everyone.
I saw how to draw a depth map from these line in source code:
![image](https://user-images.githubusercontent.com/28338959/63934733-9d9d2880-ca8e-11e9-934a-d142020c3687.png)
But does the parameter "depth"  represent absolute distance from the camera to the object?And what is the unit of distance?
If I'm wrong, how can I get the absolute distance?
Thank you a lot~

**Comment by dwofk** [comment]
Hi @MRinel,

The depth output by the network, when running `pred = model(input)`, is in meters. 

The `colored_depthmap` function simply scales the depth for visualization purposes.

**Comment by MRinel** [comment]
Thank you for your explanation! @dwofk 
There is another issue I don't quite understand. On TX2, when I use the example image, the prediction was really good [like the first image], but not so good using my own input [like the second image].I compared the input images' information, they have different depth bit, one is 32 bits, the other is 24 bits, does the last 8 bits representing transparency have any impact on prediction?
![rgb_pred](https://user-images.githubusercontent.com/28338959/64063000-eab10400-cc20-11e9-912b-70d9c3d28681.png)
![13](https://user-images.githubusercontent.com/28338959/64063016-1b913900-cc21-11e9-8f80-1148b20db011.png)

**Comment by dwofk** [comment]
Hi @MRinel,

If there is an alpha/transparency channel present (i.e. if your current input is in RGBA color space), that channel needs to be removed first, so that the correct R, G, and B channels can then be fed into the network.

You could try [converting your input from RGBA to RGB](https://stackoverflow.com/questions/50331463/convert-rgba-to-rgb-in-python) to see if this was the issue.

**Comment by MRinel** [comment]
Hi @dwofk ,
I have transformed "deploy/data/rgb.npy,pred.npy,depth.npy" to "rgb.png,pred.png,GT-depth.png" by "data/visualize.py", they are normal like what posted on fast-depth paper. But when using my current input (without alpha channel), the outputs of visualize.py seems strange. Like next pictures.
The first image is original without alpha channel, second is "visualize.py-->rgb",third is "visualize.py-->pred", I'm confused  why the RGB image  cannot be restored with visualize.py .Am I getting the npy file the right way？
I get the npy file this way:
`  from PIL import Image
  import numpy as np
 
  im = Image.open('./data/test_0902.png')
  im = im.resize((224,224),Image.ANTIALIAS)
  im_array = np.array(im)
  np.save('./data/test_0902.npy',im_array)`
![test_0902](https://user-images.githubusercontent.com/28338959/64074887-ca964900-cce3-11e9-8857-4bfaf9276724.png)
![test_0902 (1)](https://user-images.githubusercontent.com/28338959/64074888-d41fb100-cce3-11e9-9360-e2a262aa743f.png)
![test_0902_pred](https://user-images.githubusercontent.com/28338959/64074893-dbdf5580-cce3-11e9-9d54-bf0ce5f08192.png)

**Comment by MRinel** [comment]
I've solved the problem,thanks a lot! @dwofk

**Comment by aghasaadmohammad** [comment]
@MRinel how did u solve this issue?

**Comment by MRinel** [comment]
@aghasaadmohammad ,  the strange visualization of depth image seems to be related with normalization of input image. Use matplotlib for reading input or /255. have a try :)
