### ISSUE TITLE
Different frameworks between pytorch and chainer in pruning

### ISSUE THREAD

**Issue by MRinel** [dwofk/fast-depth#15]
Hi, @dwofk @fangchangma 
I have noticed that the pruning of fast-depth used Netadapt whose framework is in chainer.  Did you transform the model first into a chainer model and then do prunning?  Or is mobilenet pruned first and then combined with decoder as a pre-training model and pruned last?
I may not describe it very clearly, the two processes I want to say about pruning are:
`fast-depth(pytorch)-->fast-depth(chainer)-->prunning`
OR
`mobilenet(chainer)-->prunning-->mobilenet-pruned(pytorch)-->+decoder-->training-->fast-depth(chainer)-->prunning`
Maybe the second one is complex. Could you give me some advice? Thanks a lot!

**Comment by dwofk** [comment]
Hi @MRinel,

The NetAdapt framework we used has just been released here: https://github.com/denru01/netadapt
Please try using that instead.

For reference, we did not use chainer. We also did not split the network to prune the encoder separately. We directly fed the entire FastDepth network as input to the NetAdapt algorithm.
