### ISSUE TITLE
No module named dataloaders.dataloader - Running Evaluation code

### ISSUE THREAD

**Issue by EstebanTlelo** [dwofk/fast-depth#17]
Hi, the problem is that when i run the Evaluation Code it appears:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    args = utils.parse_command()
  File "/[My_direction_path]/utils.py", line 15, in parse_command
    from dataloaders.dataloader import MyDataloader
ImportError: No module named dataloaders.dataloader

I think the problem is in file linking. Can anybody help me?

**Comment by dwofk** [comment]
Hi @EstebanTlelo 

Are you running main.py from the top level folder of the repository?
