### ISSUE TITLE
Potential bug in data augmentation

### ISSUE THREAD

**Issue by leonoverweel** [dwofk/fast-depth#21]
Hi, I'm working on a TensorFlow implementation of [Wofk et al. (2019)](https://arxiv.org/pdf/1903.03273), and I ran into something that I think may be a bug.

In `train_transform()`, the colors of the RGB image get jittered [as follows](https://github.com/dwofk/fast-depth/blob/b6be826456476673ae718964d18bb39718e6ed4f/dataloaders/nyu.py#L26):

```python
rgb_np = self.color_jitter(rgb_np) # random color jittering
```

This calls the `color_jitter()` method, [defined in `NYUDataset`'s parent `MyDataLoader`](https://github.com/dwofk/fast-depth/blob/b6be826456476673ae718964d18bb39718e6ed4f/dataloaders/dataloader.py#L46):

```python
color_jitter = transforms.ColorJitter(0.4, 0.4, 0.4)
```

Note that it passes three parameters.

`ColorJitter` is then [defined as follows](https://github.com/dwofk/fast-depth/blob/b6be826456476673ae718964d18bb39718e6ed4f/dataloaders/transforms.py#L526):

```python
class ColorJitter(object):
    """Randomly change the brightness, contrast and saturation of an image.
    Args:
        brightness (float): How much to jitter brightness. brightness_factor
            is chosen uniformly from [max(0, 1 - brightness), 1 + brightness].
        contrast (float): How much to jitter contrast. contrast_factor
            is chosen uniformly from [max(0, 1 - contrast), 1 + contrast].
        saturation (float): How much to jitter saturation. saturation_factor
            is chosen uniformly from [max(0, 1 - saturation), 1 + saturation].
        hue(float): How much to jitter hue. hue_factor is chosen uniformly from
            [-hue, hue]. Should be >=0 and <= 0.5.
    """
    def __init__(self, brightness=0, contrast=0, saturation=0, hue=0):
        self.brightness = brightness
        self.contrast = contrast
        self.saturation = saturation
        self.hue = hue
```

The fourth parameter, `hue`, is not passed, so it defaults to zero. This seems odd; so I was wondering if this is intended behavior or a bug?

**Comment by dwofk** [comment]
Hi @leonoverweel,

This did not manifest as a bug in our training. Different combinations of jitter did not seem to make a significant difference in our results.

**Comment by leonoverweel** [comment]
Hi @dwofk, thanks for getting back to me! I've also run some experiments with different hue jitter settings and I came to the same conclusion; the results all ended up roughly within the same error bounds.
