### ISSUE TITLE
How test it on KITTI？

### ISSUE THREAD

**Issue by FireflyInwater** [dwofk/fast-depth#26]
hi，I  really appreciate your this work.But how does it perform on the KITTI dataset？
 Do you have the pre-trained model for KITTI？or can you tell me how to apply it on KITTI？
I look forward to your reply！
Good luck！

**Comment by dwofk** [comment]
Hi @FireflyInwater 

We have not trained or tested on KITTI. To apply our work on KITTI scenes, the model needs to be retrained on the KITTI dataset.

**Comment by rafiqul713** [comment]
Hi@Diana
I trained the model on KITTI dataset. But the error rate is very high.
