### ISSUE TITLE
The links of the data and model can not be opened!!

### ISSUE THREAD

**Issue by YingjieYin** [dwofk/fast-depth#32]
I can't open the links of the data and model as follows:
http://datasets.lids.mit.edu/fastdepth/data/nyudepthv2.tar.gz
http://datasets.lids.mit.edu/fastdepth/results/

**Comment by IntanP** [comment]
> I can't open the links of the data and model as follows:
> http://datasets.lids.mit.edu/fastdepth/data/nyudepthv2.tar.gz
> http://datasets.lids.mit.edu/fastdepth/results/

I can't open the links too

**Comment by xmba15** [comment]
@dwofk Can you please check this?

**Comment by dwofk** [comment]
Hi @YingjieYin @IntanP @xmba15,

Sorry about this. I am currently looking into it and will let you know as soon as this is fixed. Thanks for letting me know.

**Comment by dwofk** [comment]
@YingjieYin @IntanP @xmba15 

The server is back up now and the links should work now.

**Comment by xmba15** [comment]
@dwofk I could download the data now. Thank you very much!

**Comment by PascPeli** [comment]
I can download the dataset and the weights but when I try to open the weights I get 
`Loading the archive ‘/mobilenet-nnconv5dw-skipadd.pth.tar’ failed with the following error: Archive corrupted or insufficient permissions`. 
or  
`tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors`.
What should I do?

**Comment by donbonjenbi** [comment]
hi @dwofk - I'm having the save issue (the downloaded files can't be opened).  could you please double check if this server issue is happening again?

**Comment by xiaoliangbai** [comment]
The tar.gz file seems was damaged. I downloaded it twice, all got error on invalid format:
...
nyudepthv2/train/kitchen_0051/00216.h5

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
