### ISSUE TITLE
Pretrained encoder weights

### ISSUE THREAD

**Issue by daeyun** [dwofk/fast-depth#5]
Hi,

I'm wondering if you plan on releasing this file used to initialize training (I think):

`imagenet/results/imagenet.arch=mobilenet.lr=0.1.bs=256/model_best.pth.tar`

Or is this available somewhere else?

Thanks,
Daeyun

**Comment by dwofk** [comment]
Hi @daeyun 

Here is a download link: [https://www.dropbox.com/sh/84saro5yqc5hlgp/AABJATSwfRIfNIh0fqWVVIV1a?dl=0](https://www.dropbox.com/sh/84saro5yqc5hlgp/AABJATSwfRIfNIh0fqWVVIV1a?dl=0
)
