### ISSUE TITLE
Cannot download the pretrained model

### ISSUE THREAD

**Issue by kaanaksit** [dwofk/fast-depth#50]
```shell
wget -r -np -nH --cut-dirs=2 --reject "index.html*" http://datasets.lids.mit.edu/fastdepth/results/
```
returns `robots.txt`.

**Comment by Anne-ClaireFouchier** [comment]
I had the same issue and in the end I just used :

wget http://datasets.lids.mit.edu/fastdepth/results/mobilenet-nnconv5dw-skipadd-pruned.pth.tar |

**Comment by kaanaksit** [comment]
Thanks Anne-Claire! That resolved it.
