### ISSUE TITLE
I wonder if this model could handle any size of input or resize into 224x224 as input? 

### ISSUE THREAD

**Issue by Hackerlil** [dwofk/fast-depth#6]

**Comment by dwofk** [comment]
Hi @Hackerlil 

This model requires a 224x224 input to the first layer. Resizing a larger input to 224x224 would work.

**Comment by Hackerlil** [comment]
ok, another question,the nyudepthv2 val folder,the raw hdf5 file contains depth files,the depth info is between about 0.0 and 10.0, I want to save it for other format,such as 0-255 gray or .pgm files,means normalize.can it works?

**Comment by fangchangma** [comment]
@Hackerlil Not sure if we follow your question perfectly. Turning a float-point representation into 8-bit char should work in principle (with proper scaling), but at the cost of precision loss. It also requires retraining of the networks.
