### ISSUE TITLE
How to train models?

### ISSUE THREAD

**Issue by SiYeon-Kwon** [dwofk/fast-depth#60]
I want to use these code but I can't use because they don't have any train.py or training method.
How can I train fast-depth?

**Comment by fangchangma** [comment]
The training of FastDepth was built on top of https://github.com/fangchangma/sparse-to-dense.pytorch

**Comment by SiYeon-Kwon** [comment]
> The training of FastDepth was built on top of https://github.com/fangchangma/sparse-to-dense.pytorch

I've already referred to the git, and the training is going well. However, the calculation of mse and mae results in a figure of 0.0000. What should I do with this?

**Comment by microboym** [comment]
@SiYeon-Kwon How is the model trained?
