### ISSUE TITLE
NYUv2 preprocessed data link doesn't work

### ISSUE THREAD

**Issue by awsaf49** [dwofk/fast-depth#69]
@dwofk Hi, 
The download link provided in the readme doesn't work, is there any alternative link?
` http://datasets.lids.mit.edu/fastdepth/data/nyudepthv2.tar.gz`

**Comment by awsaf49** [comment]
As the download link doesn't work, here are alternative links for the data,
1. Kaggle: https://www.kaggle.com/datasets/awsaf49/official-split-dataset (depth dtype=`uint16`)
1. HuggingFace Dataset: https://huggingface.co/datasets/sayakpaul/nyu_depth_v2 (depth dtype=`float32`)

**Comment by fangchangma** [comment]
The server is now alive.
