### ISSUE TITLE
The version of TVM used in fast-depth and model transformation pipline

### ISSUE THREAD

**Issue by MRinel** [dwofk/fast-depth#7]
**Does  `mobilenet-nnconv5dw-skipadd-pruned.pth.tar` has been optimized or compiled by Specific version of TVM?** 
For deploying, when i use TVM0.6, there will be an error with the function "get_nums_output", i have checked that in TVM0.6 and there's an extra function "get_nums_output". But when i use TVM0.4, error occurs: 
`"Operator {} not implemented.".format(op_name)) NotImplementedError: Operator Upsample not implemented.`
Probably these all due to TVM version.
**In addition,i use the pipeline to deploy:** 
`mobilenet-nnconv5dw-skipadd-pruned.pth.tar-->onnx model-->TVM deploy model`
Is there any advice to model transformation?

**Comment by dwofk** [comment]
Hi @MRinel, 

We used a version of TVM that was between v0.4 and v0.5. To get the specific version of TVM used in our pipeline, please do:

```
git clone --recursive https://github.com/dmlc/tvm
cd tvm
git reset --hard ab4946c8b80da510a5a518dca066d8159473345f
git submodule update --init
```

You could then proceed with building TVM as specified [here](https://docs.tvm.ai/install/from_source.html#build-the-shared-library).

Operators are defined in `tvm/nnvm/python/nnvm/frontend/onnx.py`. You can search that file for `class Upsample(OnnxOpConverter)`. In older versions of TVM, the Upsample operator had not yet been implemented, which may explain why you are seeing a NotImplementedError. In the version specified above, this operator had been added.

For our work, we modified this operator slightly to:

```
class Upsample(OnnxOpConverter):
    """ Operator converter for Upsample (nearest mode).
    """

    @classmethod
    def _impl_v7(cls, inputs, attr, params):
        scales = attr.get('scales')
        #assert len(scales) == 4 and scales[0] == 1.0 and scales[1] == 1.0 and scales[2] == scales[3]
        mode = attr.get('mode')
        if mode == b'nearest':
            method = "NEAREST_NEIGHBOR"
        elif mode == b'bilinear':
            method = "BILINEAR"
        else:
            raise ValueError("Invalid ONNX upsample mode: {}".format(mode))
        return _sym.upsampling(inputs[0], scale=2, method=method, layout='NCHW')
```

After modifying this file, you would need to rerun the [Python package installation](https://docs.tvm.ai/install/from_source.html#python-package-installation).

Yes, the pipeline we used was `mobilenet-nnconv5dw-skipadd-pruned.pth.tar --> onnx model --> compile/deploy with TVM`. We performed auto-tuning for CPU and GPU backends using [AutoTVM](https://docs.tvm.ai/tutorials/autotvm/tune_relay_cuda.html).
