### ISSUE TITLE
Where is the link of 'pretrained->model_best.pth.tar' in models.py

### ISSUE THREAD

**Issue by Yvette1993** [dwofk/fast-depth#9]
@fangchangma 
Hi,
In your models.py file:
 if pretrained:
            pretrained_path = os.path.join('imagenet', 'results', 'imagenet.arch=mobilenet.lr=0.1.bs=256', 'model_best.pth.tar')
            checkpoint = torch.load(pretrained_path)

The model_best.pth.tar is pretrained weight of Mobilenet?
 Would you please give the link of 'model_best.pth.tar'. Thank you very much.

**Comment by dwofk** [comment]
Hi @Yvette1993,

Here is a download link:
https://www.dropbox.com/sh/84saro5yqc5hlgp/AABJATSwfRIfNIh0fqWVVIV1a?dl=0

**Comment by Yvette1993** [comment]
Excuse me. This link can't be opened. Would you please give an effective connection?　
Thank you very much.

**Comment by dwofk** [comment]
Were you trying to `wget` that link? Please try this instead:

```
cd fast-depth/imagenet
mkdir results; mkdir results/imagenet.arch=mobilenet.lr=0.1.bs=256
cd results/imagenet.arch=mobilenet.lr=0.1.bs=256
wget -cO - https://www.dropbox.com/s/7j9xsch121moghw/model_best.pth.tar?dl=0 > model_best.pth.tar
```

**Comment by Yvette1993** [comment]
Excuse me. 
When I running the command get:
                      failed: Connection timed out.
                      failed: Network is unreachable.

Would you please tell me the gateway information or other ways to get .pth.tar.
Thank you very much!!!

**Comment by fangchangma** [comment]
The link is working fine, so I suspect that the problem is Dropbox being blocked in your area? We will put it on our MIT server soon.

**Comment by Yvette1993** [comment]
Excuse me.
Would you please tell me when you upload pretrained model data to MIT server?

Thank you very much.

**Comment by dwofk** [comment]
The pretrained model can now be downloaded from [http://datasets.lids.mit.edu/fastdepth/imagenet/](http://datasets.lids.mit.edu/fastdepth/imagenet/). 

Please let us know if you have trouble with this link.

**Comment by Yvette1993** [comment]
It's work!!! 
Thank you very much.
